version: '3.5'

services:
  app:
    build:
      context: ./
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - "8000:5000"
    volumes:
      - ./app:/usr/src/app
    networks:
      - app_net
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    # volumes:
    #   - .docker/database/dump:/sql
    #   - .docker/database/data:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net: